abstract final class AppRoutes {
  static const loading = '/loading';
  static const signIn = '/sign-in';
  static const invitationPending = '/invitation-pending';
  static const accessDenied = '/access-denied';
  static const configurationError = '/configuration-error';
  static const error = '/error';
  static const admin = '/admin';
  static const adminHome = '$admin/home';
  static const adminLeads = '$admin/leads';
  static const adminNewLead = '$adminLeads/new';
  static const adminTasks = '$admin/tasks';
  static const adminMore = '$admin/more';
  static const sales = '/sales';
  static const salesHome = '$sales/home';
  static const salesLeads = '$sales/leads';
  static const salesNewLead = '$salesLeads/new';
  static const salesTasks = '$sales/tasks';
  static const salesMore = '$sales/more';
}
